include:
  - template: Security/Secret-Detection.gitlab-ci.yml

image: node:latest

variables:
  GO_VERSION: "1.21.1"

stages:
  - lint
  - deploy

secret_detection:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

renovate:
  stage: lint
  image: ghcr.io/renovatebot/renovate:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: $CI_API_V4_URL
    RENOVATE_TOKEN: $CI_JOB_TOKEN
    LOG_LEVEL: info
  script:
    - renovate $CI_PROJECT_PATH

build:
  stage: deploy
  script:
    - apt-get update && apt-get install -y wget tar
    - wget https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz
    - tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
    - rm go${GO_VERSION}.linux-amd64.tar.gz
    - export PATH=$PATH:/usr/local/go/bin
    - npm --version
    - npx --version
    - go version
    # Without checking out main first Cloudflare will treat the source as HEAD and deploy to Preview instead of Production.
    - git checkout main
    - go run main.go build
    - npx --yes wrangler pages deploy ./dist --project-name millhouse-dev
  only:
    - main
  except:
    - schedules
